// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxkDwD4g9J29h-r08-gTwMmXH6TwAuBs0',
    appId: '1:894222229853:web:06f53eaae5666378a148b4',
    messagingSenderId: '894222229853',
    projectId: 'farmerapp-bad99',
    authDomain: 'farmerapp-bad99.firebaseapp.com',
    storageBucket: 'farmerapp-bad99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZD6UQbDx3ESWzxmWn1WtEaEGJgCDdYdg',
    appId: '1:894222229853:android:5c5be516c4026138a148b4',
    messagingSenderId: '894222229853',
    projectId: 'farmerapp-bad99',
    storageBucket: 'farmerapp-bad99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAYWwZnJkfFNSa4U8HKV20KDSDauPX92w',
    appId: '1:894222229853:ios:c370b6687ef80d05a148b4',
    messagingSenderId: '894222229853',
    projectId: 'farmerapp-bad99',
    storageBucket: 'farmerapp-bad99.firebasestorage.app',
    iosBundleId: 'com.agrotech.agroconnect.agroconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAYWwZnJkfFNSa4U8HKV20KDSDauPX92w',
    appId: '1:894222229853:ios:c370b6687ef80d05a148b4',
    messagingSenderId: '894222229853',
    projectId: 'farmerapp-bad99',
    storageBucket: 'farmerapp-bad99.firebasestorage.app',
    iosBundleId: 'com.agrotech.agroconnect.agroconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxkDwD4g9J29h-r08-gTwMmXH6TwAuBs0',
    appId: '1:894222229853:web:1cdf24024689c68ba148b4',
    messagingSenderId: '894222229853',
    projectId: 'farmerapp-bad99',
    authDomain: 'farmerapp-bad99.firebaseapp.com',
    storageBucket: 'farmerapp-bad99.firebasestorage.app',
  );
}
